In [4]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr=np.array((2,3,4,5))
print(arr)
print(type(arr))

[2 3 4 5]
<class 'numpy.ndarray'>


# o dimenasion array

In [5]:
arr=np.array(30)
print(arr)
print(arr.ndim)

30
0


# 1 dimention array

In [6]:
arr=np.array([2,3,4,5,])
print(arr)
print(arr.ndim)

[2 3 4 5]
1


# 2 dimention array

In [8]:
arr=np.array(([1,2,3,3],[5,4,5,6]))
print(arr)
print(arr.ndim)

[[1 2 3 3]
 [5 4 5 6]]
2


# 3 dimention array

In [10]:
arr=np.array((([2,3,4,],[5,6,7]),([6,5,6,],[8,7,8])))
print(arr)
print(arr.ndim)

[[[2 3 4]
  [5 6 7]]

 [[6 5 6]
  [8 7 8]]]
3


In [11]:
arr=np.array((([1,2,3],[4,5,6]),([7,8,9],[3,4,5])))
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 4 5]]]


# check no. of dimention

In [21]:
a=np.array(20)

b=np.array([2,3,4])

c=np.array(([1,2,3],[4,5,6]))

d=np.array((([1,2,3],[4,5,6]),([7,8,9],[11,12,13])))

print(a.ndim)

print(b.ndim)

print(c.ndim)

print(d.ndim)

0
1
2
3


# CREATE AN ARRAY OF 5 DIMENTION AND VERUFY THAT IT HAS 5 DIMENTION

In [5]:
arr=np.array((1,2,3,4),ndmin=5)
print(arr)
print("the dimentin of this array is",arr.ndim)


[[[[[1 2 3 4]]]]]
the dimentin of this array is 5


In [6]:
arr=np.array((1,2,3,4,5),ndmin=5)
print(arr)
print("number of dimention: " ,arr.ndim)
print(type(arr))

[[[[[1 2 3 4 5]]]]]
number of dimention:  5
<class 'numpy.ndarray'>


# array indexing

In [8]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print("the ist element of a is", a[0])

[1 2 3 4 5 6 7 8]
the ist element of a is 1


# ADD THE IST ANMD LAST ELEMENT OF IST ROW


In [9]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print("ist element of ist row is",arr[0,0])
print("last elemnt of ist row is",arr[0,3])
print("sum of both are",arr[0,0]+arr[0,3])

ist element of ist row is 10
last elemnt of ist row is 40
sum of both are 50


# checking the data type of an array

In [8]:
arr=np.array([1,2,3,4,5,56,6])
print(arr)
print(arr.dtype)

[ 1  2  3  4  5 56  6]
int32


In [13]:
arr=np.array(["ss","sss","ssjnsdjdd"])
print(arr.dtype)

<U9


# PRINT THE SHAPE OF 2-D ARRAY

In [15]:
arr=np.array(([1,2,3],[3,4,5],[5,6,4]))
print(arr)
print(arr.shape)

[[1 2 3]
 [3 4 5]
 [5 6 4]]
(3, 3)


# joining arrays

In [19]:
arr1=([2,3,4,2,5])
arr2=([4,5,6,4])
join=np.concatenate((arr1,arr2))
print(join)

[2 3 4 2 5 4 5 6 4]
