# INTRODUCTION OF NUMPY

NUMPY(NUMERICAL PYHTON) IS AN OPEN SOURCE PYTHON LIBRARY THAT IS USED ALMOST EVERY FIELD OF SCIIENCE AND ENGEERING.
IT IS THE UNIVERSAL STANDARD FOR WORKING WITH NUMERICAL DATA IN PYTHON, AN DIT IS AN CORE OF SCIENTIFIC PYHTON AND
PYDATA ECOSYSTEMS.

THE NUMPY LIBRARY CONTAIN A MULTIDIMENTIONAL ARRAY AND MTRIX DATA STRUCTURE

NUMPY CAN BE USED TO PERFORM A WIDE VARIETY OF MATHEMATICAL OPERATIONS ON ARRAYS.
IT ADDS POWERFUL DATA STRUCTURES TO PYTHON THAT GUARANCE EFFICIENT CALCULATION WITH
ARRAY AND MATHEMETICAL AND ITS SUPPLIES AN ENORMOUS LIBRARY OF HIGH LEVEL MATHEMATICAL
FUNCTIONS THAT OPERATEON THESE ARRAY AND MATRICES.

IT ALSO HAS FUNCTION  FOR WORKING IN DOMAIN OF LINEAR ALGEBRA,FORRIER TRASFORMATION MATRICES NUMPY 
WAS CREATED IN 2005 BY TRVIS OLIPHANT.IT IS AN OPEN SOURCE AND YOU CAN USE IT FREELY.

# WHY USE NUMPY

IN PYHTON WE HAVE LIST THAT SRVES THE PURPOSE OF ARRAYS, BUT THEY ARE SLOW TO PROCESS.

NUMPY AIMS TO PROVIDE AN ARRAY OBJECDT THAT IS UP 50X FASTER THAN TRADICTIONAL PYHTON LISTS.

THE ARRAY OBJECTS IN PYTHON IS CALLED ND ARRAY,IT PRIVIDES A LOT OF SUPPORTING FUNTION THAT MAKES WORKING WITH ND ARRAY EASY.

ARRAY ARE VERY FREQUENTLY USES IN DATA SCIENCE, WHERE SPEED AND RESOURCE IS IMPORTANT.

# WHY IS NUJMPY IS FASTER THAN LIST

NUMPY ARRAY ARE STORED AT ONE CONTINOUS PLACE IN MEMERY UNLIKE LIST, SO PROCESS CAN ACCES AND MANUPLATE THEM EFFICIENTLY.

THIS BEHAVIOR IS CALLED LOCALITY OF REFERENCE ON COMPURT SCIENCE.

THIS IS THE MAIN REASON WHY.......

# CREATING NUMPY LIBRARY

In [22]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# TO CREATE AN ndarray, WE CAN PASS A LIST, TUPLE OR ANY ARRAY LIKE ONJECT INTO THE ARRAY()METHOD, AN DIT WILL BE
CONVERTED ONTO AN ndarray:

In [4]:
import numpy as np
arr=np.array((1,2,3,4,5,6))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


# DIMENTIONS IN ARRAY

O-d array with value 20

In [5]:
arr=np.array(20)
print(arr)

20


# 1-D ARRAY

1-D ARRAY IS AN ARRAY THAT HAS 0-D ARRAY AS ITS ELEMENT IS CALLED UNIDIMENTIONAL ORN1-D ARRAY.

In [6]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2-D ARRAY

In [12]:
arr=np.array(([1,2,3,4],[5,6,7,8]))
print(arr)
print(type(arr))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [15]:
arr=np.array(([1,2,3,4],[5,6,7,8]))
print(arr)
print(type(arr))
print(arr.ndim)#for getting the dimention of array 

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [16]:
arr=np.array(([1.1,2.2,3.3,4],[5,6,7,8]))
print(arr)
print(type(arr))
print(arr.ndim)#for getting the dimention of array 

[[1.1 2.2 3.3 4. ]
 [5.  6.  7.  8. ]]
<class 'numpy.ndarray'>
2


#    3-ARRAY

AN ARRAY HAS 2-D ARRAY(MATRICES) AS ITS ELEMENT IS CALLED 3-D ARRAY

In [21]:
arr=np.array((((1,2,3),(4,5,6)),((1,2,3),(4,5,6))))
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


# CHECK NO. OF DIMENTION

In [28]:
a=np.array(10)
b=np.array((1,2,3))
c=np.array(((1,2,3),(4,5,6)))
d=np.array((((1,2,3),(1,2,3)),((4,5,6,),(4,5,6))))

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# HIGHER DIMENTIONAL ARRAY

AN ARRAY CAN HAVE ANY NO OF DIMENTIONS

WHEN THE ARRAY IS CREATED,U CAN DEFINE THE NO. OF DUMENTION BY USING ndim ARGIMENTS

# CREATE AN ARRAY OF 5 DIMENTION AND VERUFY THAT IT HAS 5 DIMENTION

In [43]:
arr=np.array((1,2,3,4,5),ndmin=5)
print(arr)
print("number of dimention: " ,arr.ndim)
print(type(arr))

[[[[[1 2 3 4 5]]]]]
number of dimention:  5
<class 'numpy.ndarray'>


# NumPy ARRAY INDEXING

ARRAY INDEXING IS SAME AS ACCESSING ARRAY ELEMENT

YOU CAN ACCESS TO AN ARRAY ELEMNT BY REFFRING TO ITS INDEX NO.

THE INDEX NO. IN NumPy START WITH 0

# GET THE FIRST ELEMENT FORM THE ARRAY

In [9]:
arr=np.array((1,2,3,4,5))
print(arr)
print("THE ISt ELEMEMT IS: ")
print("the ist element is:",arr[0])

[1 2 3 4 5]
THE ISt ELEMEMT IS: 
the ist element is: 1


# GET THE 3,7,and 8 THREE ELEMENT FRO THE ARRAY AND ADD THEM

In [51]:
m=((33,44,55,67,32,45,67,23,11,98,43,54,26,32))
print("the third element of array is: ",m[2])
print("the seventh element of array is: ",m[6])
print("the eirth element of array is: ",m[7])
print("the sum of all three element is:",m[2]+m[6]+m[7])

the third element of array is:  55
the seventh element of array is:  67
the eirth element of array is:  23
the sum of all three element is: 145


# ACCESSING 2-D ARRAY

TO ACCESS ELEMENT FROM 2-D ARRAY WE CAN USE COMMA SEPERTAED INTEGERS REPRESENTING THE DIMENTION AND THE INDEX OF THE ELEMENT.

THINK OF 2-D ARRAY LIKE A TABLE WITH RAW AND COLUMN,WHEN THE DIMENTION REPRESENT THE ROW AND THE INDEX REPRESENT THE COLOMN

In [56]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print("third element of ist row:",arr[0,2])#we r accessing third no. element

third element of ist row: 30


In [58]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print("second element of second row:",arr[1,1])

second element of second row: 60


In [62]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print("second element of ist row:",arr[0,1])


second element of ist row: 20


# ADD THE IST ANMD LAST ELEMENT OF IST ROW

In [65]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print("ist element of ist row:",arr[0,1])
print("last element of ist row:",arr[0,3])
print("SUM OF IST AND LAST ELEMENT OF IST ROW:",arr[0,1]+arr[0,3])

ist element of ist row: 20
last element of ist row: 40
SUM OF IST AND LAST ELEMENT OF IST ROW: 60


# ACCESSING 3-D ARRAYS

TO ACCESS ELEMENT FROM 3-D ARRAY WE CAN USE COMMA SEPERTAED INTEGERS REPRESENTING THE DIMENTION AND THE INDEX OF THE ELEMENT.

In [67]:
#we are tyying to get the ist element of row 2 and sub row 1
x=np.array((((1,2,3),(4,5,6,)),((7,8,9,),(10,11,12))))
print("the ist element of 2nd row of sub row ist:",x[1,0,0])

the ist element of 2nd row of sub row ist: 7


In [68]:
x=np.array((((1,2,3),(4,5,6,)),((7,8,9,),(10,11,12))))
print("the 2nd element of ist row of sub row 2nd:",x[0,1,1])

the 2nd element of ist row of sub row 2nd: 5


# NEGATIVE INDEXDIING

In [1]:
import numpy as nu

In [3]:
arr=nu.array((1,2,3,4,5))
print(arr[-3])

3


In [4]:
import numpy as np

In [6]:
arr=nu.array(((1,2,3,4,5),(2,3,4,5,6,)))
print("last element of row 2 is:",arr[1,-1])

last element of row 2 is: 6


# NUMPY ARRAY SLICING

SLICING IS ARRAY MEANS TAKIONG ELEMENT FROM ONE GIVEN INDEX TO ANOTHER GIVEN INDEX.

WE PASS SLICE INSTEAD OF INDEX LIKE THIS: [START:END].

WE CAN ALSO DEFINED THE STEP, LIKE THIS:[START:END:STEP].

# SLICING ELEMENT FROM 1 TO 5 FROM GIVEN ARRAY

In [8]:
import numpy as np

In [10]:
ar=((1,2,3,4,5,6,7,8))
print(ar[1:6])

(2, 3, 4, 5, 6)


In [4]:
import numpy as np

In [6]:

a=np.array([2,3,4,5,6,7,8])
b=a[0:3]
print(a)
print(b)

[2 3 4 5 6 7 8]
[2 3 4]


SLICING ELEMENT FROM INDEX 4 TO LAST OF ARRAY

In [11]:
ar=((1,2,3,4,5,6,7,8))
print(ar[4:])

(5, 6, 7, 8)


STEPPING ONE ELEMMNTS

In [12]:
ar=((1,2,3,4,5,6,7,8))
print(ar[::2])

(1, 3, 5, 7)


# SLICING 2-D ARRAY

In [17]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print(arr[1, 0:2])

[50 60]


In [7]:
a=np.array(([1,2,3],[5,6,7]))
print(a)
print(a[0,0:2])

[[1 2 3]
 [5 6 7]]
[1 2]


In [14]:
arr=np.array(((10,20,30,40),(50,60,70,80)))
print(arr[0,2:])

[30 40]


# SLICING IN 3D ARRAY

In [8]:
arr=np.array((([1,2,3],[4,5,6]),([7,6,5],[4,5,6])))
print(arr)
sl=arr[0,0,1:]
print(sl)

[[[1 2 3]
  [4 5 6]]

 [[7 6 5]
  [4 5 6]]]
[2 3]
