# NUMPY PART 2

DATA TYPES IN PYTHON , BY DEFAULT PYTHON HAVE THESE TYPES OF DATA

STRING,  INTEGER, FLOAT, BOOLEAN

In [ ]:
DATA TYPES IN NUMPY
NUMPY HAS SOME EXTRA DATA TYPES, AND REFER TO DATA TYPES WITH ONE CHARACTERS,

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - deltatime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type (void)

# CHECK THE TYPE OF DATA OF AN ARRAY

In [2]:
import numpy as np

In [1]:
import numpy as np

arr=np.array((1,2,3,4,5))
print(arr.dtype)
print(type(arr))

int32
<class 'numpy.ndarray'>


In [9]:
import numpy as np

arr=np.array((1,2,3,4,5))
print(arr.dtype)

int32


In [12]:
import numpy as np
arr=np.array(("animal","name","place"))
print(arr)
print(type(arr))
print(arr.dtype)

['animal' 'name' 'place']
<class 'numpy.ndarray'>
<U6


# CREATING ARRAY WITH DEFINED DATA TYPES

In [16]:
import numpy as np

arr=np.array((1,2,3,4), dtype="S")t
print(arr.dtype)

|S1


In [5]:
arr=np.array([2,3,54,6], dtype="S")
print(arr.dtype)

|S2


In [18]:
import numpy as np

arr=np.array((1,2,3,4), dtype="i")
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [19]:
import numpy as np

arr=np.array((1,2,3,4), dtype="f")
print(arr.dtype)

float32


# CREATING A DATA TYPE WITH 4 BYTES INTEGER

In [23]:
arr=np.array((1,2,3,4,5), dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


# NUMPY ARRAY SHAPE

THE SHAPE OF AN ARRAY IS THE NO OF ELEMENT IN EACH DIMENTION

# PRINT THE SHAPE OF 2-D ARRAY

In [27]:
arr=np.array(((1,2,3,4),(5,6,7,8)))
print(arr)
print("the shape of arary",arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
the shape of arary (2, 4)


# CREATING AN ARRAY WITH 5 DIMENTION USING NDIM USING A VECTOR WITH VALUES 1,2,3,4 AND VERIFY THAT LAST DIMENTION HAS 4 VALUES:

# JOINING  NUMPY ARRAY(concatenate)

In [31]:
import numpy as np

arr1=np.array((1,2,3,4))
arr2=np.array((5,6,7,8))
arr3=np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [5]:
import numpy as np

arr1=np.array((1,2,3,4))
arr2=np.array((5,6,7,8))
print(np.concatenate((arr1,arr2)))



[1 2 3 4 5 6 7 8]


# JOINING 2-D ARRAY ALONG ROW (AXIS 1)ROWS

In [7]:
import numpy as np

arr1=np.array(([1,2],[3,4]))
arr2=np.array(([5,6],[7,8]))
arr3=np.concatenate((arr2,arr2),axis=1)


# JOINING 2-D ARRAY ALONG ROW (AXIS 1)COLUMN

In [ ]:
import numpy as np


# SPLITING NUMPY ARRAYS

SPLITING   IS THE REVERSE OPERATION OF JOINING

JOINING MERGES MULTIPLE ARRAYS INTO ONE AND SPLITING BREAKS ONE ARRAY INTO MULTIPLE

# SPLIT THE ARRAY IN n PARTS

In [6]:
arr=np.array((1,2,3,4,5,6))
arrr=np.array_split(arr,2)
print(arrr)

[array([1, 2, 3]), array([4, 5, 6])]


In [8]:
arr=np.array((1,2,3,4,5,6))
arrr=np.array_split(arr,4)
print(arrr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [7]:
arr=np.array((1,2,3,4,5,6))
print(np.array_split(arr,2))


[array([1, 2, 3]), array([4, 5, 6])]


# REVEL AND FLATTEN - CONVERTS MULTIDIMENTIONAL ARRAY INTO 1 ARRAY

In [63]:
x=np.array((((1,2,3),(4,5,6)),((7,8,9),(1,2,3))))
print(x)
print("dimention is",x.ndim)
print()
y=x.flatten()
print(y)
print(" new dimention is:",y.ndim)
#ravel and flatten work are same

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
dimention is 3

[1 2 3 4 5 6 7 8 9 1 2 3]
 new dimention is: 1


In [64]:
x=np.array((((1,2,3),(4,5,6)),((7,8,9),(1,2,3))))
print(x)
print("dimention is",x.ndim)
print()
y=x.ravel()
print(y)
print(" new dimention is:",y.ndim)
#ravel and flatten work are same

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
dimention is 3

[1 2 3 4 5 6 7 8 9 1 2 3]
 new dimention is: 1


# ARITHMETIC OPERATION IN NUMPY ARRAYS

# ADDITION

In [77]:
arr=np.array((1,2,3,4,5))
arrr=arr+3
print(arrr)

[4 5 6 7 8]


In [78]:
x=np.array((1,2,3,4))
y=np.array((1,2,3,4))
print(x+y)

[2 4 6 8]


In [80]:
x=np.array((1,2,3,4))
y=np.array((1,2,3,4))
z=np.add(x,y)
print(z)

[2 4 6 8]


# SUBTRACTION

In [81]:
arr=np.array((5,2,7,4,5))
arrr=arr-3
print(arrr)

[ 2 -1  4  1  2]


In [3]:
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
print(x-y)


[-1  3  0  0]


In [9]:
import numpy as np
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
z=np.subtract(x,y)
print(z)

[-1  3  0  0]


# MULTIPLICATION

In [11]:
x=np.array((3,2,4,6))
y=x*2
print(y)

[ 6  4  8 12]


In [12]:
x=np.array((3,2,4,6))
print(x*2)

[ 6  4  8 12]


In [13]:
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
z=x*y
print(z)

[ 2 18  9 16]


In [15]:
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
z=np.multiply(y,x)
print(z)

[ 2 18  9 16]


# DIVISION

In [18]:
x=np.array((6,8,7,5,6))
print(x/2)

[3.  4.  3.5 2.5 3. ]


In [21]:
x=np.array((6,8,7,5,6))
y=2
z=x/y
print(z)

[3.  4.  3.5 2.5 3. ]


In [22]:
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
z=x/y
print(z)

[0.5 2.  1.  1. ]


In [23]:
x=np.array((1,6,3,4))
y=np.array((2,3,3,4))
z=np.divide(x,y)
print(z)

[0.5 2.  1.  1. ]


# MODULOUS

In [27]:
x=np.array((10,15,25,30))
y=3
z=x%y
print(z)
#modulous gives us remainder

[1 0 1 0]


In [28]:
x=np.array((10,15,25,30))
print(x%2)


[0 1 1 0]


In [29]:
x=np.array((10,15,25,30))
y=np.array((3,4,5,6))
z=x%y
print(z)

[1 3 0 0]


In [30]:
x=np.array((32,14,15,26))
y=np.array((3,4,5,6))
print(np.mod(x,y))


[2 2 0 2]


# ARITHMETIC OPERATION IN 2-D ARRAY

In [31]:
n1=np.array(((1,2,3,4),(5,6,7,8)))
n2=np.array(((1,2,3,4),(5,6,7,8)))
x=n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [32]:
n1=np.array(((1,2,3,4),(5,6,7,8)))
n2=np.array(((1,2,3,4),(5,6,7,8)))
x=n1-n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [33]:
n1=np.array(((1,2,3,4),(5,6,7,8)))
n2=np.array(((1,2,3,4),(5,6,7,8)))
x=n1*n2
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


In [34]:
n1=np.array(((1,2,3,4),(5,6,7,8)))
n2=np.array(((1,2,3,4),(5,6,7,8)))
x=n1/n2
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# ARITHMETIC OPERATION IN 3-D ARRAY

In [36]:
x=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
y=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
z=x+y
print(z)


[[[ 2  4  6  8]
  [10 12 14 16]]

 [[ 2  4  6  8]
  [10 12 14 16]]]


In [37]:
x=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
y=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
z=np.add(x,y)

print(z)

[[[ 2  4  6  8]
  [10 12 14 16]]

 [[ 2  4  6  8]
  [10 12 14 16]]]


In [38]:
x=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
y=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
z=x-y
print(z)


[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


In [39]:
x=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
y=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
z=x*y
print(z)


[[[ 1  4  9 16]
  [25 36 49 64]]

 [[ 1  4  9 16]
  [25 36 49 64]]]


In [40]:
x=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
y=np.array((((1,2,3,4),(5,6,7,8)),((1,2,3,4),(5,6,7,8))))
z=x/y
print(z)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# UNIQUE FUNCTION

unique fn gives us unique element or non repeated element

In [42]:
arr=np.array((3,4,5,6,7,8,7,6,89,12,34,23,54,65,23,12,34,23,43,3,4,9,10,3,30,11))
print("the unique values are:",np.unique(arr))

the unique values are: [ 3  4  5  6  7  8  9 10 11 12 23 30 34 43 54 65 89]


In [43]:
arr=np.array((3,4,5,6,7,8,7,6,89,12,34,23,54,65,23,12,34,23,43,3,4,9,10,3,30,11))
print(arr)
x=np.unique(arr, return_index=True)
print(x)

[ 3  4  5  6  7  8  7  6 89 12 34 23 54 65 23 12 34 23 43  3  4  9 10  3
 30 11]
(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 23, 30, 34, 43, 54, 65, 89]), array([ 0,  1,  2,  3,  4,  5, 21, 22, 25,  9, 11, 24, 10, 18, 12, 13,  8],
      dtype=int64))


In [44]:
arr=np.array((3,4,5,6,7,8,7,6,89,12,34,23,54,65,23,12,34,23,43,3,4,9,10,3,30,11))
print(arr)
print()
x=np.unique(arr, return_index=True, return_counts=True)
print(x)

[ 3  4  5  6  7  8  7  6 89 12 34 23 54 65 23 12 34 23 43  3  4  9 10  3
 30 11]

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 23, 30, 34, 43, 54, 65, 89]), array([ 0,  1,  2,  3,  4,  5, 21, 22, 25,  9, 11, 24, 10, 18, 12, 13,  8],
      dtype=int64), array([3, 2, 1, 2, 2, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1, 1, 1], dtype=int64))


# DELETE FUNCTION

In [48]:
a=np.array((12,13,14,15,16))
print(a)
print()
print("new array is:",np.delete(a,[1]))

[12 13 14 15 16]

new array is: [12 14 15 16]


In [61]:
a=np.array(((12,13,14,15),(12,14,25,26),(2,3,4,5)))
print(a)
print()
print(np.delete(a,1,axis=1))

[[12 13 14 15]
 [12 14 25 26]
 [ 2  3  4  5]]

[[12 14 15]
 [12 25 26]
 [ 2  4  5]]


In [62]:
a=np.array(((12,13,14,15),(12,14,25,26),(2,3,4,5)))
print(a)
print()
print(np.delete(a,1,axis=0))

[[12 13 14 15]
 [12 14 25 26]
 [ 2  3  4  5]]

[[12 13 14 15]
 [ 2  3  4  5]]
